Added a crmscript for setting interests for contact.
SuperOfficeDocs/superoffice-docs pull request #1144
Opened 2024-04-12 10:07 UTC by ejfasting

Also added some clarification to the interests.md for the minimal number of items needed for headings to show, or how you can define preferences for this in admin.

2024-04-12 10:52 UTC, SuperOfficeDevNet requested changes

2024-04-12 10:52 UTC, SuperOfficeDevNet commented on docs/en/company/toc.yml
The indenting on this file has changed, and now incorrect. 
Please restore the indenting.

2024-04-12 11:02 UTC, digitaldiina requested changes
Great with more CRMScript examples, @ejfasting 🎉 Please look through my suggested edits for grammar, clarity, and brevity.

2024-04-12 13:02 UTC, digitaldiina commented on docs/en/company/howto/crmscript/set-interest-on-off-crmscript.md
> +
```suggestion
```

Remove heading without content

2024-04-12 13:03 UTC, digitaldiina commented on docs/en/company/interests.md
> +
```suggestion

```

Remove double line break

2024-04-12 13:11 UTC, digitaldiina commented
@ejfasting we have a simple CRMScript example for person interests (contact/howto/crmscript/get-interests.md) Might be useful to connect these pages. Also, consider expanding get-interests.md.

2024-04-12 14:52 UTC, ejfasting commented
@digitaldiina good idea! I'll update with some additional things :)

2024-04-16 08:59 UTC, digitaldiina requested changes

2024-04-16 08:59 UTC, digitaldiina commented on docs/en/contact/interests.md
> +The `person` table has a counter field that stores the number of active interests. This field is used to cache the count. It is updated whenever the user edits the contact. The field is used to quick
```suggestion
The `person` table has a counter field that stores the number of active interests. This field is used to cache the count. It is updated whenever the user edits the contact. The field is used to quickly check whether the **Interests** tab needs to indicate the presence of interests or not.
```

2024-04-16 08:59 UTC, digitaldiina commented on docs/en/contact/interests.md
> +> [!NOTE]
```suggestion

> [!NOTE]
```

Always space before note/tip

2024-04-16 08:59 UTC, digitaldiina commented on docs/en/contact/howto/crmscript/set-interest-on-off-crmscript.md
> +uid: crmscript-set-interests-on-off
uid must be *unique*, suggest 'crmscript-set-interest-contact' or 'crmscript-set-contact-interest' and to change accordingly in the company  file

2024-04-16 08:59 UTC, digitaldiina commented on docs/en/contact/howto/crmscript/set-interest-on-off-crmscript.md
> +title: Set interests
should be the same as H1

2024-04-16 08:59 UTC, digitaldiina commented on docs/en/company/media/company-interests.png
Not too happy with dummy names. Examples should look real if possible.

2024-04-16 08:59 UTC, digitaldiina commented on docs/en/contact/media/contact-interests.png
Create better test data, please - or you can use my tenant for the screenshots.

2024-04-16 08:59 UTC, digitaldiina commented on docs/en/contact/howto/crmscript/set-interest-on-off-crmscript.md
> +keywords: CRMScript, contact, interests
```suggestion
keywords: CRMScript, contact, interest
```

2024-04-16 08:59 UTC, digitaldiina commented on docs/en/contact/interests.md
Conceptually, interests are "the same". Please keep the content on a single page and rather use headings to distinguish contact and company interests. This will facilitate linking and search and simplify planned content restructuring (need less redirects).

2024-04-18 10:27 UTC, closed without merging