1289 add documentation for flush
SuperOfficeDocs/superoffice-docs pull request #1290
Opened 2024-08-14 11:51 UTC by ejfasting

Added documentation for what flushing the application actually does behind the scenes. Updated/Referenced this flush-caches.md in places where its relevant to flush (webpanels/extra-fields).

2024-08-14 13:58 UTC, digitaldiina requested changes

2024-08-14 13:58 UTC, digitaldiina commented on docs/en/api/caching/flush-cache.md
> +* SystemInfo
Please sort alphabetical

2024-08-14 13:58 UTC, digitaldiina commented on docs/en/api/caching/flush-cache.md
> +Refreshes all language resources.
A list?

2024-08-14 13:58 UTC, digitaldiina commented on docs/en/api/web-services/howto/custom-objects/rest-create-udef-field.md
> +> Depending on the user-case it might be a good idea to [flush caches][4]
```suggestion
> Depending on the user-case it might be a good idea to [flush caches][4].
```

2024-08-14 13:58 UTC, digitaldiina commented on docs/en/api/web-services/howto/custom-objects/rest-delete-udef-field.md
> +> Depending on the user-case it might be a good idea to [flush caches][4]
```suggestion
> Depending on the user-case it might be a good idea to [flush caches][4].
```

2024-08-14 13:58 UTC, digitaldiina commented on docs/en/api/web-services/howto/custom-objects/rest-update-udef-field.md
> +> Depending on the user-case it might be a good idea to [flush caches][4]
```suggestion
> Depending on the user-case it might be a good idea to [flush caches][4].
```

2024-08-14 13:58 UTC, digitaldiina commented on docs/en/ui/web-panels/index.md
> +> After adding a webpanel it is good practice to [flush caches][4] in the application
```suggestion
> After adding a webpanel it is good practice to [flush caches][4] in the application.
```

2024-08-19 08:27 UTC, digitaldiina approved these changes

2024-08-22 08:16 UTC, SuperOfficeDevNet approved these changes

2024-08-22 08:16 UTC, merged