1536 10.3.13 release notes
SuperOfficeDocs/superoffice-docs pull request #1538
Opened 2024-12-03 14:29 UTC by kirstiaa

Minor changes for the 10.3.13 release.

2024-12-04 13:35 UTC, digitaldiina requested changes
Please update the release date in the metadata header too.

2024-12-04 13:35 UTC, digitaldiina commented on release-notes/10.3/index.md
> +* **Tenant manager** - separate pages to help manage and view customer (tenant) information, including authorizations and licenses, across different environments like development and production.
I suggest to use same names as in the portal, meaning SOD and not development

2024-12-04 14:23 UTC, kirstiaa reviewed
Done changing meta data information

2024-12-05 08:11 UTC, digitaldiina approved these changes
✅

2024-12-05 08:11 UTC, merged