Consolidate NetServer config
SuperOfficeDocs/superoffice-docs pull request #164
Opened 2021-12-10 14:20 UTC by digitaldiina

Goes with https://github.com/SuperOfficeDocs/data-access/pull/86

2021-12-16 14:28 UTC, AnthonyYates commented on docs/automation/netserver-scripting/configure.md
> +The *SoAppConfig.exe* utility will use the [Scripting section][1] of the NetServer configuration.
```suggestion
The *SoAppConfig.exe* utility sets the [Scripting section][1] of the NetServer configuration.
```

2021-12-16 14:35 UTC, digitaldiina commented on docs/automation/netserver-scripting/configure.md
> +The *SoAppConfig.exe* utility will use the [Scripting section][1] of the NetServer configuration.
fixed

2021-12-16 14:43 UTC, AnthonyYates commented on docs/marketing/forms/recaptcha.md
>  </GoogleRecaptcha>
Create an issue to add GoogleRecaptcha section to the Configuration article?

2021-12-16 14:54 UTC, AnthonyYates commented on docs/mobile/pocket-crm/configure.md
> +To enable this feature in NetServer make sure that *web.config* contains this element:
Where in the web.config?

AllwaysUseGsmPhoneStyle is in [globalization](https://docs.superoffice.com/api/netserver/config/globalization.html)

2021-12-16 15:03 UTC, AnthonyYates commented on docs/mobile/pocket-crm/deploy.md
> +[7]: ../../../../data-access/docs/netserver/config/soformsauthentication.md
This link is declared, but not used anywhere. Please place it in the NOTE section referencing the web.config file.

2021-12-16 18:09 UTC, AnthonyYates commented on docs/onsite/debug/web-client.md
> +> This is not a debug log for MailLink.
If there is a debug log setting for MailLink, link to it from here.

2021-12-16 18:32 UTC, AnthonyYates commented on docs/onsite/install/index.yml
>        links:
This file should be reference in /docs/onsite/toc.yml

- name: Install Onsite
  href: index.yml
  items:

2021-12-16 18:34 UTC, AnthonyYates commented on docs/onsite/install/netserver/index.md
>  NetServer is always installed, but for some scenarios, we recommend it is installed as remote web services.
Could use an elaboration for what scenarios it is recommended to install as remote web services.

2021-12-16 18:39 UTC, digitaldiina commented on docs/onsite/install/netserver/index.md
>  NetServer is always installed, but for some scenarios, we recommend it is installed as remote web services.
See issue #169

2021-12-16 18:52 UTC, AnthonyYates commented on docs/onsite/install/win-client/superoffice-config.md
Moving files around (moving authors cheese) is not cool without verbal agreement.

2021-12-16 18:59 UTC, AnthonyYates commented on docs/onsite/toc.yml
>    - name: Config
Please eliminate shortened words in TOC. This section contains "Configuration" or "Configuration Settings".  Conversely, avoid more then two words if possible.

2021-12-16 19:16 UTC, AnthonyYates commented on docs/onsite/upgrade/to-81/using-old-service-domain.md
> +2. Run the **SuperOffice.CustomerService.exe** file to upgrade Service software.
```suggestion
2. Run **SuperOffice.CustomerService.exe** to upgrade Service software.

```

2021-12-16 19:21 UTC, AnthonyYates commented on docs/service/config/service-config.md
> +title: Service config
What's the meaning of this empty page?

2021-12-16 19:23 UTC, AnthonyYates commented on docs/service/install/index.md
> +1. Run the SuperOffice.CustomerService.exe file.
```suggestion
1. Run SuperOffice.CustomerService.exe to begin.

```

2021-12-16 19:27 UTC, AnthonyYates commented on docs/service/install/index.md
>  [Previous][15] | [Next][14] | [Back to guide][13]
Do these really go where to relevant places? From here, next navigates to Install Web. Is that the correct order?

2021-12-16 19:29 UTC, AnthonyYates commented on docs/service/install/manual-steps.md
> +Run the SuperOffice.CustomerService.exe file to install the software on the server, the default location is *c:\superoffice*.
```suggestion
Run SuperOffice.CustomerService.exe to install the software on the server, the default location is *c:\superoffice*.

```

2021-12-16 19:32 UTC, AnthonyYates commented on docs/travel/toc.yml
> +  - name: Config
Please change name to "Configuration" or "Configuration settings". 

Do not change folder names.

2021-12-16 19:37 UTC, AnthonyYates commented on docs/travel/travel-gateway/username-ini.md
> +> It adds the associate ID when you ask for other users and will check the database for this associate's current user group.
Moving someones cheese again... 😨

2021-12-16 19:40 UTC, AnthonyYates requested changes
I've made some comments that need changes.

Moving files into other folders without mutual consent is forbidden. This must be discussed with Martin prior to approval.

2021-12-16 19:41 UTC, SuperOfficeDevNet requested changes
See my other comments.

2021-12-17 14:10 UTC, SuperOfficeDevNet approved these changes

2021-12-17 14:10 UTC, merged