214 refactor diary
SuperOfficeDocs/superoffice-docs pull request #243
Opened 2022-03-22 11:20 UTC by digitaldiina

Changes at a glance:

- co-located conceptual info
- improved navigation and index pages
- updated category page with 4 new cards
- moved 3 tutorials from api/tutorials to diary/tutorials and changed to yml format

2022-03-23 15:09 UTC, SuperOfficeDevNet requested changes
Just have a few broken links to fix, then we can merge this in. 

Good work! 🥇

2022-03-23 15:09 UTC, SuperOfficeDevNet commented on docs/diary/tutorials/rss-feed-vb/index.yml
> +    <a href="../../assets/downloads/api/rssfeedfinalvb.zip" download>Click to download source code (zip)</a>
Download link fails... change to (it works):
```markdown
[Click to download source code (zip)](~/assets/downloads/api/rssfeedfinalvb.zip)
```

2022-03-23 18:33 UTC, SuperOfficeDevNet commented on docs/diary/index.yml
> +        url: ../automation/trigger/reference/CRMScript.Event.Trigger.yml#CRMScript_Event_Trigger_SalesBeforeSaveAppointmen
This link needs fixing:
url: ../automation/trigger/reference/CRMScript.Event.Trigger.yml#CRMScript_Event_Trigger_SalesBeforeSaveAppointmen
to
url: ../automation/trigger/reference/CRMScript.Event.Trigger.yml#CRMScript_Event_Trigger_SalesBeforeSaveAppointment

2022-03-24 12:28 UTC, digitaldiina commented
Links updated @SuperOfficeDevNet

2022-03-24 14:33 UTC, merged