Remove pic. from DKIM key example
SuperOfficeDocs/superoffice-docs pull request #403
Opened 2022-08-24 07:11 UTC by pavlas77

2022-08-24 07:55 UTC, digitaldiina requested changes

2022-08-24 07:55 UTC, digitaldiina commented on docs/email/mailgun/dkim/set-up.md
> +    * Add "Host name" value (e.g. "xxx._domainkey.[yourdomainName]") you received from us.
Don't use Latin abbreviations on docs. Also, "e.g." means "for example", and since what follows is a pattern and not an example it's better to leave it out.

2022-08-24 09:50 UTC, pavlas77 commented on docs/email/mailgun/dkim/set-up.md
> +    * Add "Host name" value (e.g. "xxx._domainkey.[yourdomainName]") you received from us.
Done

2022-08-26 07:35 UTC, digitaldiina approved these changes
Thanks for the fixes :)

2022-08-26 07:36 UTC, merged