Update checklist.md
SuperOfficeDocs/superoffice-docs pull request #465
Opened 2022-09-26 07:13 UTC by MargretheR

All users are on SuperID now - updated systemuser warning about associates.

2022-09-28 09:02 UTC, digitaldiina requested changes
Delete line 54. No double blank lines to keep the linter happy.

2022-09-29 06:14 UTC, SuperOfficeDevNet approved these changes

2022-09-29 06:14 UTC, SuperOfficeDevNet approved these changes

2022-09-29 06:15 UTC, SuperOfficeDevNet approved these changes

2022-09-29 06:20 UTC, merged