454 release notes 10.1.6
SuperOfficeDocs/superoffice-docs pull request #468
Opened 2022-09-28 12:03 UTC by kirstiaa

#454 New release 10.1.6 and new information for this release.

2022-09-29 10:47 UTC, digitaldiina requested changes

2022-09-29 10:47 UTC, digitaldiina commented on release-notes/10.1/core-crm/10.1.6-update.md
> +## Company and Contact – Note with date and time stamp
This must be added to core-crm/index.md also

2022-09-29 10:47 UTC, digitaldiina commented on release-notes/10.1/core-crm/10.1.6-update.md
> +![Contact (and Company) - Note tab - Add a time stamp with a button][img4]
-screenshot is missing in the image tag

2022-09-29 12:58 UTC, SuperOfficeDevNet requested changes
Just a couple comments and suggestions. However, the comment about removing all unnecessary pronouns would suggest there are a few other changes needed to improve readability and reduce noise.

2022-10-03 12:18 UTC, digitaldiina approved these changes
gtg

2022-10-03 12:45 UTC, merged