209 configurable screens
SuperOfficeDocs/superoffice-docs pull request #486
Opened 2022-10-20 08:28 UTC by digitaldiina

- New section for Screen Designer
- Fixed some linting issues in *ui* folder related to line length

2022-10-20 13:15 UTC, SuperOfficeDevNet requested changes
Good first draft. Some sections seemed unchanged from the spec. Please review my suggestions and make appropriate adaptations.

2022-10-20 13:15 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/index.md
> +* Columns: Choose how many columns (1-4) the fields and elements may occupy.
```suggestion
* Columns: Lists column layout options to contain fields and elements.

```

2022-10-20 13:15 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/index.md
> +To open the Screen Designer, go to **Settings and maintenance** and select **Screen Designer** from the navigator.
Link to how/where to locate Settings and maintenance menu link.

2022-10-20 13:15 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/index.md
> +> After you publish a layout, users assigned to it must sign out of SuperOffice and back in to see the changes.
```suggestion
> After a layout is published, user groups assigned to it must sign out of SuperOffice and back in to see the changes.

```

2022-10-20 13:15 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/index.md
> +If you need to revert to an earlier version of the screen, you can access the following options from the **Task** button:
```suggestion
Use the **Task** button to revert to an earlier version of the screen.

```

2022-10-20 13:15 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/index.md
> +* **Reset to factory settings:** This option discards all changes and resets the screen layout to the standard layout delivered by SuperOffice.
```suggestion
* **Reset to factory settings:** This option discards all changes and resets the screen layout to the default (system) layout delivered by SuperOffice.

```

2022-10-20 13:15 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/index.md
> +Without the Development Tools license, new cards take effects and the custom fields are displayed in two columns.
> Without the Development Tools license, new cards take effects and the custom fields are displayed in two columns.

What?

2022-10-21 09:57 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/add-button.md
> +> If you require any other protocol than HTTP, you must explicitly add it to the URL.
HTTP was the default when I tested in SOD

2022-10-21 10:06 UTC, digitaldiina commented on docs/ui/screen-designer/index.md
> +> After you publish a layout, users assigned to it must sign out of SuperOffice and back in to see the changes.
It's not the group that must sign out. Thus going with the pattern, the text should be "user in groups assigned to it"

2022-10-21 10:07 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/working-with-fields.md
> +You can give easy access to important custom fields by adding or moving them to the main (left-most) tab. You can also move less important fields to secondary tabs as an alternative to removing them.
'Conversely' is not in the vocabulary of non-native English speakers.

2022-10-21 10:11 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/add-layout.md
> +When you delete a custom layout, user groups assigned to it are reassigned to the system layout.
'user group' is two words when not part of adjective

2022-10-21 11:02 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/working-with-fields.md
> +1. Select the tab you want to add the field to.
no, passive

2022-10-21 11:08 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/assign-layout.md
> +If you delete a layout, user groups assigned to it, will go back to the default layout.
edited

2022-10-21 14:26 UTC, SuperOfficeDevNet requested changes

2022-10-21 14:26 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/configurable-screens/assign-layout.md
> +If you delete a layout, user groups assigned to it, will go back to the default layout.
No edits are not observed.

2022-10-21 14:26 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/configurable-screens/working-with-fields.md
> +1. Select the tab you want to add the field to.
Revise the statement without the pronoun.

2022-10-21 14:41 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/index.md
> +> After you publish a layout, users assigned to it must sign out of SuperOffice and back in to see the changes.
That's fine, however, stating "users assigned to it", what is 'it'? How about:

After a layout is published, users who are a member of the assigned user-groups must sign out of SuperOffice and back in to see the changes.

2022-10-24 06:59 UTC, digitaldiina commented on docs/ui/screen-designer/index.md
> +Without the Development Tools license, new cards take effects and the custom fields are displayed in two columns.
revised

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/index.md
> +> After you publish a layout, users assigned to it must sign out of SuperOffice and back in to see the changes.
"layout is published" is passive, 2nd clause is revised

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/index.md
> +To open the Screen Designer, go to **Settings and maintenance** and select **Screen Designer** from the navigator.
added

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/working-with-tabs.md
> +If you reduce the number of columns, the fields will be moved to the new last column. For example, If you change from three to two, all fields in the third column are moved to the bottom of column 2.
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/working-with-tabs.md
> +Whether you've added a tab that's become irrelevant or there's a tab some or all groups in your organization doesn't use, it can likely be removed.
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/working-with-fields.md
> +To reduce clutter, it is useful to hide fields that are never used (either by the organization or a specific user group). The field and its contents remains in the database even tho it's not shown.
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/working-with-fields.md
> +You can give easy access to important custom fields by adding or moving them to the main (left-most) tab. You can also move less important fields to secondary tabs as an alternative to removing them.
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/working-with-fields.md
> +1. Select the tab you want to add the field to.
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/index.md
> +User-defined fields (udef) and extra fields are created as before.
links added

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/index.md
> +The **More** tab has all custom fields ordered by rank. You probably want to go through and organize these. You can add important custom fields other places.
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/index.md
> +In addition, you can [add custom layouts][2] and assign them to a user group. Layouts in the **Sales** screen can alternatively be assigned to a **sales type**. Layouts in the **Project** screen can
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/edit-card-layout.md
> +When you are done, click one of the following buttons:
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/edit-card-layout.md
> +> You can also modify the **default layout** of one or more screens for all users to fit the specific needs of your organization. However, you can't edit the settings and you can't re-assign it.
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/assign-layout.md
> +If you delete a layout, user groups assigned to it, will go back to the default layout.
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/add-layout.md
> +When you delete a custom layout, user groups assigned to it are reassigned to the system layout.
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/add-button.md
> +You can add, edit, and remove translations later. But remember to republish the layout.
edited

2022-10-24 07:00 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/add-button.md
> +Add custom buttons and links to the same areas you can add fields to. You can add URLs for looking up information in other websites, allow users to run CRMScripts from the screen, and add navigation
"where fields are added" is passive

2022-10-27 10:33 UTC, SuperOfficeDevNet requested changes
Getting close!

2022-10-27 10:33 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/configurable-screens/working-with-tabs.md
> +If you reduce the number of columns, the fields are moved to the new last column. For example, when reducing the number of columns from three to two, all fields in the third column move to the bottom
An epic addition of content to docs such as this is understandable taxing. Especially the review phase. Try to remain vigilant with tense, and phrasing.

```suggestion
If you reduce the number of columns, the fields are moved to the new last column. For example, when reducing the number of columns from three to two, all fields in the third column move to the bottom of column 2. When reduced to one column, all fields move to the first column.

```

2022-11-14 08:07 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/configurable-screens/add-button.md
> +Add custom buttons and links to the same areas you can add fields to. You can add URLs for looking up information in other websites, allow users to run CRMScripts from the screen, and add navigation
Will accept some changes.

2022-11-14 08:17 UTC, SuperOfficeDevNet requested changes

2022-11-14 08:17 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/configurable-screens/add-button.md
> +Add custom buttons and links to the same areas you add fields to. The URL is used to open a webpage in the current or new tab, run a CRMScript from the screen, or navigate to other parts of SuperOffi
Custom buttons and links are added to the preview pane...

2022-11-14 08:17 UTC, SuperOfficeDevNet commented on docs/ui/screen-designer/configurable-screens/add-button.md
> +> If you require any other protocol than HTTP, you must explicitly add it to the URL.
```suggestion
> It's recommended to specify the protocol, for example https://www.secure.com, otherwise the default is HTTP.
```

2022-11-14 09:04 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/add-button.md
> +Add custom buttons and links to the same areas you add fields to. The URL is used to open a webpage in the current or new tab, run a CRMScript from the screen, or navigate to other parts of SuperOffi
Commit 7a95a98

2022-11-14 09:04 UTC, digitaldiina commented on docs/ui/screen-designer/configurable-screens/add-button.md
> +> If you require any other protocol than HTTP, you must explicitly add it to the URL.
Commit 7a95a98

2022-11-14 12:38 UTC, SuperOfficeDevNet approved these changes

2022-11-14 12:43 UTC, merged