#494 Added new method
SuperOfficeDocs/superoffice-docs pull request #496
Opened 2022-10-28 07:58 UTC by kronicz

closing #494

2022-10-28 10:20 UTC, SuperOfficeDevNet requested changes
Nice addition to the library! Would you be so kind as to add a an entry in the [Map DataType](https://github.com/SuperOfficeDocs/superoffice-docs/blob/main/docs/automation/crmscript/datatypes/map-type.md) information page? 

This would make a good addition under the current Map.Get description in that page.

2022-11-03 08:04 UTC, digitaldiina requested changes

2022-11-03 08:04 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Native.Map.yml
> +      - id: key
Incorrect yml indentation of parameters lines 228-233

2022-11-03 09:14 UTC, digitaldiina approved these changes

2022-11-03 09:17 UTC, digitaldiina commented
Good to go from me, @kronicz.

2022-11-14 07:42 UTC, SuperOfficeDevNet approved these changes

2022-11-14 07:43 UTC, merged