update mailgun process
SuperOfficeDocs/superoffice-docs pull request #506
Opened 2022-11-04 09:56 UTC by fbhub2

update a detail on How to configure with your own SMTP

2022-11-14 09:23 UTC, digitaldiina reviewed
Word "customer" is ambiguous here. The topic is already addressed to the SuperOffice customer  by saying *configure your CRM Online site*.

2022-11-14 09:24 UTC, digitaldiina requested changes

2022-11-14 09:24 UTC, digitaldiina commented on docs/email/mailgun/overview.md
> +Customer needs to contact our support directly, and they will help you to get it configured.
```suggestion
Contact our support directly, and they will help you to get it configured.

```

2022-11-17 12:48 UTC, SuperOfficeDevNet approved these changes

2022-11-17 12:49 UTC, merged