#511 Added new class file
SuperOfficeDocs/superoffice-docs pull request #512
Opened 2022-11-11 11:13 UTC by kronicz

Closing #511

2022-11-14 09:16 UTC, digitaldiina requested changes
* Please create a page for the new Long datatype in the crmscript/datatypes folder, similar to http://docs.superoffice.com/automation/crmscript/datatypes/integer-type.html
* Add the new Float constructur to the Float datatype page.
* Add the new String.toLong() method to the String datatype page.
* List of Long children should be alphabetical
* Should have so.version on all new methods

2022-11-14 13:55 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.Long.yml
> +  summary: "\nReturn the high 32 bits Integer of the Long.\n"
```suggestion
  summary: "\nReturns the high 32-bit Integer of the Long.\n"
```

2022-11-15 12:59 UTC, digitaldiina requested changes
A few minor updates, most should slide right in. Don't forget to create long-type.md in the datatypes folder.

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.yml
>    - CRMScript.Global.Integer
I sorts before L

```suggestion
  - CRMScript.Global.Integer
  - CRMScript.Global.Long
```

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.Integer.yml
> +  summary: "\nIntegers are positive and negative whole 32bit unsigned numbers without decimals. If you need to work with decimals, use the Float data type.\n"
```suggestion
  summary: "\nIntegers are positive and negative whole 32-bit unsigned numbers without decimals. If you need to work with decimals, use the Float data type.\n"
```

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/datatypes/float-type.md
> +### Float Float(Long value)
Move this method before *Float Float(String number)* so that it directly follows the Integer constructor.

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.Float.yml
> +  - CRMScript.Global.Float.#ctor(Long)
```suggestion
  - CRMScript.Global.Float.#ctor(Long)
  - CRMScript.Global.Float.#ctor(String)
```

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.String.yml
> +  summary: "\nConvert the given String to a Long. If the number in the String is outside the bounds of a Long, it will become the highest or lowest possible number.\n"
```suggestion
  summary: "\nConverts a String to a Long. If the number in the String is outside the bounds of a Long, it will become the highest or lowest possible number.\n"
```

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.String.yml
> +  summary: "\nConvert the given String to a Long. If the number in the String is outside the bounds of a Long, it will become the highest or lowest possible number.\n"
What does "highest or lowest possible number" mean specifically? Which one is it, and what is the value? How will the creator of the CRMScript know the string was out of bounds?

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.Long.yml
> +  summary: "\Longs are positive and negative whole 64bit unsigned numbers without decimals. If you need to work with decimals, use the Float data type.\nTo represent a long number in the code as a li
```suggestion
  summary: "\Longs are positive and negative whole 64-bit unsigned numbers without decimals. If you need to work with decimals, use the Float data type.\nTo represent a long number in the code as a literal, suffix it with an &quot;L&quot;, for example, &quot;Long l = 576460752303423488L;&quot;"
```

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.Long.yml
> +  - "\n<pre><code>Long i;\nprintLine(i.isNull().toString());\ni = 0;\nprintLine(i.isNull().toString());</code></pre>\nThe 1st output will be true because we haven't initialized ì yet.\nThe next outpu
```suggestion
  - "\n<pre><code>Long i;\nprintLine(i.isNull().toString());\ni = 0;\nprintLine(i.isNull().toString());</code></pre>\nThe first output will be true because we haven't initialized i yet.\nThe next output will be false because i now has the value 0.\n"
```

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.Long.yml
> +  summary: "\nReturn the low 32-bit Integer of the Long.\n"
```suggestion
  summary: "\nReturns the low 32-bit Integer of the Long.\n"
```

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.Long.yml
> +  summary: "\Longs are positive and negative whole 64bit unsigned numbers without decimals. If you need to work with decimals, use the Float data type.\nTo represent a long number in the code as a li
```suggestion
  summary: "\nLongs are positive and negative whole 64bit unsigned numbers without decimals. If you need to work with decimals, use the Float data type.\nTo represent a long number in the code as a literal, suffix it with an &quot;L&quot;, e.g. &quot;Long l = 576460752303423488L;&quot;"
```

2022-11-15 12:59 UTC, digitaldiina commented on docs/automation/crmscript/reference/CRMScript.Global.Long.yml
> +- uid: CRMScript.Global.Long
overwritten uid

```suggestion
- uid: CRMScript.Global.Integer
```

2022-11-16 06:47 UTC, kronicz commented on docs/automation/crmscript/reference/CRMScript.Global.String.yml
> +  summary: "\nConvert the given String to a Long. If the number in the String is outside the bounds of a Long, it will become the highest or lowest possible number.\n"
Basically means highest possible value (9223372036854775807) or highest negative value (-9223372036854775807) of Long.

2022-11-18 09:31 UTC, merged