601 10.2.2 whats new
SuperOfficeDocs/superoffice-docs pull request #614
Opened 2023-02-10 11:51 UTC by kirstiaa

The changes for the 10.2.2 version is updated - 3 files that is changed/added + images.

I did also update some sections for Sales target, since it was not added any info about Targets only for Online customers, the Onsite customers will not get access to this feature. Updated both in Learn and in Release notes 10.1.x.

Have not been able to build locally, to check the changes made for 10.2.2. 

Hopefully will this be merged and released by Tuesday 14th February 2023. Thanks!

2023-02-10 13:50 UTC, SuperOfficeDevNet requested changes
Correct the noted mistake.

2023-02-10 13:50 UTC, SuperOfficeDevNet commented on release-notes/10.2/admin/index.md
> +* [Email domain validation (10.2.1)][2]
I think you meant to write (10.2.2) here... as that is the link version...

2023-02-13 10:47 UTC, kirstiaa commented
I have change the error in version on the Admin index file.

2023-02-13 10:48 UTC, SuperOfficeDevNet approved these changes

2023-02-13 10:48 UTC, merged