Update sharepoint documents configurepermissions-document
SuperOfficeDocs/superoffice-docs pull request #678
Opened 2023-04-27 10:07 UTC by fbhub2

Update sharepoint documents configurepermissions-document with details about Confidential activities and Visible for

2023-04-27 13:29 UTC, digitaldiina requested changes
@pavlas77 A few suggestions from me. Click **Accept** if you agree. Minimum change is to not use single quotes for emphasis.

2023-04-27 13:29 UTC, digitaldiina commented on docs/en/document/cloud/sharepoint-documents/configure-permissions-documents.md
> +[1]: https://help.superoffice.com/Documentation/Help/EN/CRM/10.1/WebHelpAdmin/chap07/Adding_users_web.htm
We've migrated the admin guide to docs. Suggest you link directly to the most recent version of the **Add user** page.

```suggestion
[1]: ../../../admin/user-management/learn/add-associate.md
```

2023-04-27 13:29 UTC, digitaldiina commented on docs/en/document/cloud/sharepoint-documents/configure-permissions-documents.md
> +'Visible for' field in the [document dialog][2]: display a list that allows you to choose whether the document will be visible to all users, private (i.e. visible only to the user defined as owner),
```suggestion
* The **Visible for** field in the [document dialog][2] display a list that allows you to choose whether the document will be visible to all users, private (visible only to the user defined as owner), or visible to all users in one of the user groups that the owner belongs to. 
```

2023-04-27 13:29 UTC, digitaldiina commented on docs/en/document/cloud/sharepoint-documents/configure-permissions-documents.md
> +'Confidential activities' in the [Settings and maintenance - Users][1]: activates the 'Visible for' for the user.
```suggestion
* **Confidential activities** in the [Settings and maintenance - Users][1] activates the *Visible for* for the user.
```

2023-04-27 13:29 UTC, digitaldiina commented on docs/en/document/cloud/sharepoint-documents/configure-permissions-documents.md
> +> This feature is only relevant if 'Confidential activities' is enabled for users in 'Settings and maintenance', and 'Visible for' field is set on the the document property:
```suggestion
> This feature is relevant only if **Confidential activities** is enabled for users in Settings and maintenance, and the **Visible for** field is set on the document property:
```

2023-04-27 13:29 UTC, digitaldiina commented on docs/en/document/cloud/sharepoint-documents/configure-permissions-documents.md
> +<summary>Show details for Confidential activities and Visible for</summary>
We aim to use this syntax less and I recommend omitting it. If it's worth mentioning, there's no need to hide the info.

2023-04-27 13:40 UTC, pavlas77 commented on docs/en/document/cloud/sharepoint-documents/configure-permissions-documents.md
> +<summary>Show details for Confidential activities and Visible for</summary>
@digitaldiina  It was Frode's edits. I just asked you for a review. 

Anyway, I changed the <details> section to be visible and part of the Note. Is it ok now? 

Thanks for the info.

2023-04-28 07:43 UTC, digitaldiina approved these changes

2023-04-28 07:43 UTC, digitaldiina approved these changes

2023-04-28 07:44 UTC, digitaldiina commented on docs/en/document/cloud/sharepoint-documents/configure-permissions-documents.md
> +<summary>Show details for Confidential activities and Visible for</summary>
Thanks @pavlas77 and @fbhub2 :)

2023-04-28 07:45 UTC, merged