646 10.2.5 release notes
SuperOfficeDocs/superoffice-docs pull request #682
Opened 2023-04-28 11:33 UTC by kirstiaa

Added release notes for 10.2.5 containing
- Mobile CRM - Link to project and sale on request
- New Request/Service with Requests navigation inside the CRM module

Ready to merge to main and publish to production.
:-)

2023-04-28 13:43 UTC, digitaldiina requested changes
The topmost index.md in release-notes still says 10.2.4 is the latest

```
[**Version 10.2.4**][6] - 03.28.2023
```

2023-04-28 13:43 UTC, digitaldiina commented on release-notes/10.2/toc.yml
The new mobile version is missing in this toc.

2023-04-28 13:43 UTC, digitaldiina commented on release-notes/10.2/service/10.2.5-update.md
> +Do you not see the Requests button in the SuperOffice CRM module and you want it?
```suggestion
Do you not see the **Requests** button in the SuperOffice CRM module and you want it?
```

2023-04-28 13:43 UTC, digitaldiina commented on release-notes/10.2/service/10.2.5-update.md
> +Go to the Request screen and select Own open request in the [Find requests][2] menu. You'll get a list containing all your requests and you can easily follow up on them.
```suggestion
Go to the Requests screen and select **Own open request** in the [Find requests][2] menu. You'll get a list containing all your requests and you can easily follow up on them.
```

2023-04-28 13:43 UTC, digitaldiina commented on release-notes/10.2/service/10.2.5-update.md
> +*Overview of the requests screen/tab in the SuperOffice CRM module*
```suggestion
*Overview of the Requests screen/tab in the SuperOffice CRM module*
```

2023-04-28 13:43 UTC, digitaldiina commented on release-notes/10.2/service/10.2.5-update.md
> +![From the Main menu go to Knowledge base -screenshot][img3]
No caption?

2023-04-28 13:43 UTC, digitaldiina commented on release-notes/10.2/mobile/10.2.11-update.md
> +Read more about [request][1] on the Learn section.
```suggestion
Read more about [requests][1] in the Learn section.
```

2023-05-02 06:53 UTC, kirstiaa commented on release-notes/10.2/service/10.2.5-update.md
> +![From the Main menu go to Knowledge base -screenshot][img3]
No, don't think it's needed, since I want to highlight where to find Knowledge base, and that's under Main menu, and that it's the one I want to highlight.

2023-05-02 06:54 UTC, kirstiaa commented on release-notes/10.2/service/10.2.5-update.md
> +Go to the **Main menu** and select Knowledge base, and then select Reply templates, FAQs, External documents or E-mail addresses.
The main issue is where to look for Knowledge base, that is way I have highlighted Main menu, and not the others.

2023-05-02 14:27 UTC, digitaldiina commented on release-notes/10.2/service/10.2.5-update.md
> +To make the transition as smooth as possible between using the SuperOffice Service module and to start using Requests inside the SuperOffice CRM module, the upgrade will go in multiple waves. Meaning
I don't see a commit for this change request.

2023-05-03 10:49 UTC, digitaldiina approved these changes
Thanks for making the changes, @kirstiaa

2023-05-03 10:50 UTC, merged