Docs for CRMScript.Global.Void.authenticateCustomer
SuperOfficeDocs/superoffice-docs pull request #700
Opened 2023-05-16 13:27 UTC by hjelms

2023-05-16 13:51 UTC, digitaldiina commented on docs/en/automation/crmscript/reference/CRMScript.Global.Void.yml
> +  so.version: 10.2.25
Did you mean .5 and not .25?

```suggestion
  so.version: 10.2.5
```

2023-05-16 13:55 UTC, digitaldiina requested changes
2 minor suggestions

Builds OK:

![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/23242792/83ae7d15-2cef-4fe4-b4d2-225207b311be)


Thanks for the contribution, @hjelms !

2023-05-16 13:55 UTC, digitaldiina commented on docs/en/automation/crmscript/reference/CRMScript.Global.Void.yml
> +  summary: "\nChecks a customers username and password. Returns personId if successful, otherwise a null Integer.\n"
```suggestion
  summary: "\nChecks a customer's username and password. Returns personId if successful, otherwise a null Integer.\n"
```

2023-05-21 18:31 UTC, SuperOfficeDevNet commented
No need to nit pick obvious things.

2023-05-21 18:31 UTC, merged