Add warning about your own SMTP
SuperOfficeDocs/superoffice-docs pull request #752
Opened 2023-06-21 10:53 UTC by pavlas77

2023-06-21 10:53 UTC, pavlas77 commented
@digitaldiina Please feel free to amend the text to improve my English.

2023-06-22 12:22 UTC, SuperOfficeDevNet requested changes

2023-06-22 12:22 UTC, SuperOfficeDevNet commented on docs/en/email/mailgun/overview.md
> +> Be aware of the consequences running your own SMTP server and not using Mailgun. In this case the automated bounce handling will not work because there is no web hook from your SMTP server to our S
```suggestion
> Be aware of the consequences of running your own SMTP server and not using Mailgun. In this case the automated bounce handling will not work because there is no webhook from your SMTP server to our SuperOffice Online platform. The only way to handle bounces is to import bounce emails back to SuperOffice via inbox. That means the email address from which the emails are sent out needs to be configured as a mailbox in Service.

```

2023-06-22 12:22 UTC, SuperOfficeDevNet approved these changes

2023-06-22 12:23 UTC, merged