370 mobile crm user guide
SuperOfficeDocs/superoffice-docs pull request #803
Opened 2023-08-15 11:49 UTC by digitaldiina

2023-08-15 13:26 UTC, SuperOfficeDevNet requested changes
Just a few comments based on feedback from JP.

2023-08-15 13:26 UTC, SuperOfficeDevNet commented on docs/en/mobile/superoffice-mobile/getting-started/login.md
> +    You can also open a web browser on your device, go to[online.SuperOffice.com/mobile][3], and click **install** to choose your device type.
Add a space.

```suggestion
    You can also open a web browser on your device, go to [online.SuperOffice.com/mobile][3], and click **install** to choose your device type.
```

2023-08-15 13:26 UTC, SuperOfficeDevNet commented on docs/en/mobile/superoffice-mobile/getting-started/login.md
> +    ![Mobile CRM: set up -app-screen][img7]
This image is wrong. This we do not do anymore, it is CRM Online only.

2023-08-15 13:26 UTC, SuperOfficeDevNet commented on docs/en/mobile/superoffice-mobile/getting-started/set-up-email.md
> +# Setting up an email account
Setting up email, this is not possible anymore... Ask JP. This is how it looks now:

![image](https://github.com/SuperOfficeDocs/superoffice-docs/assets/15157161/0db68a77-62f0-4eb0-a9a7-0772ac23a835)

2023-08-16 10:44 UTC, digitaldiina commented on docs/en/mobile/superoffice-mobile/getting-started/set-up-email.md
> +# Setting up an email account
See commit https://github.com/SuperOfficeDocs/superoffice-docs/pull/803/commits/9c5152f3c277a053fb8ca1a57ef931c0d7daad59

2023-08-16 10:45 UTC, digitaldiina commented on docs/en/mobile/superoffice-mobile/getting-started/login.md
> +    ![Mobile CRM: set up -app-screen][img7]
See commit https://github.com/SuperOfficeDocs/superoffice-docs/pull/803/commits/f85bc43e9a3f8a2b0f9ef26a80c40deecd6e1619

2023-08-16 14:39 UTC, merged